### ISSUE TITLE
Versioning of XkOps

### ISSUE THREAD

**Issue by alikhanxgrid** [XgridInc/xkops#14]
**Description**
Research and propose a system for versioning of XkOps.

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
...

**Comment by SyedMurtazaHassan46** [comment]
Here is the [document](https://docs.google.com/document/d/1q6hTIRVn6Dy3FWjIeMsXDXrJQ5KRqwvNtrmUXpNsQbg/edit?usp=sharing).
